#!/bin/bash

MSG="$1"

commit_msg_type_regex='feat|fix|refactor|style|test|docs|build|chore|ci|perf|hotfix|revert'
commit_msg_scope_regex='.{1,20}'
commit_msg_subject_regex='.{1,100}'
commit_msg_regex="^(${commit_msg_type_regex})(\(${commit_msg_scope_regex}\))?: (${commit_msg_subject_regex})\$"

if	! grep -qE "$commit_msg_regex" "$MSG"; then
    echo "Your commit message must follow conventional commits, please check that https://www.conventionalcommits.org/en/v1.0.0/"
    exit 1
fi